#!/usr/bin/env python3
"""G3: Extract all LLM prompts from backend/app/ into eval/prompts-snapshot.md.

Usage:
    python scripts/extract-prompts.py           # check only; exits 1 if stale
    python scripts/extract-prompts.py --update  # regenerate snapshot
"""

from __future__ import annotations

import argparse
import ast
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
APP_DIR = REPO_ROOT / "backend" / "app"
SNAPSHOT = REPO_ROOT / "eval" / "prompts-snapshot.md"

# Variable names that conventionally hold prompts
PROMPT_VAR_PATTERN = re.compile(
    r"(?i)(system_prompt|prompt_template|instruction|node_prompt|user_prompt|PROMPT)"
)


def extract_string_assignments(src: str) -> list[tuple[str, str]]:
    """Return (variable_name, string_value) for all top-level string assignments."""
    results: list[tuple[str, str]] = []
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return results
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and PROMPT_VAR_PATTERN.search(target.id):
                    if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
                        results.append((target.id, node.value.value))
    return results


def collect_prompts() -> dict[str, list[tuple[str, str]]]:
    """Walk APP_DIR and collect all prompt assignments, keyed by relative path."""
    all_prompts: dict[str, list[tuple[str, str]]] = {}
    for py_file in sorted(APP_DIR.rglob("*.py")):
        src = py_file.read_text(encoding="utf-8")
        hits = extract_string_assignments(src)
        if hits:
            rel = str(py_file.relative_to(REPO_ROOT))
            all_prompts[rel] = hits
    return all_prompts


def build_snapshot(prompts: dict[str, list[tuple[str, str]]]) -> str:
    lines = [
        "# Prompt Snapshot",
        "",
        "Auto-generated by `scripts/extract-prompts.py`. Do not edit manually.",
        "",
        "---",
        "",
    ]
    if not prompts:
        lines += [
            "> No prompt variables found in `backend/app/` yet.",
            "",
            "This file will be populated as LLM prompt strings are added.",
            "",
        ]
    else:
        for path, assignments in prompts.items():
            lines += [f"## `{path}`", ""]
            for var, value in assignments:
                lines += [
                    f"### `{var}`",
                    "",
                    "```text",
                    value.strip(),
                    "```",
                    "",
                ]
    return "\n".join(lines)


def snapshot_is_stale(prompts: dict[str, list[tuple[str, str]]]) -> bool:
    if not SNAPSHOT.exists():
        return True
    snap_mtime = SNAPSHOT.stat().st_mtime
    for src_path in APP_DIR.rglob("*.py"):
        if src_path.stat().st_mtime > snap_mtime:
            return True
    return False


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="Regenerate snapshot")
    args = parser.parse_args()

    prompts = collect_prompts()

    if args.update:
        SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT.write_text(build_snapshot(prompts), encoding="utf-8")
        print(f"Snapshot written to {SNAPSHOT.relative_to(REPO_ROOT)}")
        sys.exit(0)

    # Check-only mode
    if snapshot_is_stale(prompts):
        print(
            "ERROR: eval/prompts-snapshot.md is stale. "
            "Run: python scripts/extract-prompts.py --update"
        )
        sys.exit(1)
    else:
        print("Prompt snapshot is up to date.")
        sys.exit(0)


if __name__ == "__main__":
    main()
